import 'package:arabic_learning_app/features/Alphabet/data/models/arabic_letter_model.dart';

const List<ArabicLetterModel> arabicLetters = [
  ArabicLetterModel(letter: 'ا', word: 'أَرْنَب', emoji: '🐰'),
  ArabicLetterModel(letter: 'ب', word: 'بَطَّة', emoji: '🦆'),
  ArabicLetterModel(letter: 'ت', word: 'تُفَّاحَة', emoji: '🍎'),
  ArabicLetterModel(letter: 'ث', word: 'ثَعْلَب', emoji: '🦊'),
  ArabicLetterModel(letter: 'ج', word: 'جَمَل', emoji: '🐫'),
  ArabicLetterModel(letter: 'ح', word: 'حِصَان', emoji: '🐴'),
  ArabicLetterModel(letter: 'خ', word: 'خَرُوف', emoji: '🐑'),
  ArabicLetterModel(letter: 'د', word: 'دَجَاجَة', emoji: '🐔'),
  ArabicLetterModel(letter: 'ذ', word: 'ذِئْب', emoji: '🐺'),
  ArabicLetterModel(letter: 'ر', word: 'رُمَّان', emoji: '🍒'),
  ArabicLetterModel(letter: 'ز', word: 'زَرَافَة', emoji: '🦒'),
  ArabicLetterModel(letter: 'س', word: 'سَمَكَة', emoji: '🐟'),
  ArabicLetterModel(letter: 'ش', word: 'شَمْس', emoji: '☀️'),
  ArabicLetterModel(letter: 'ص', word: 'صَقْر', emoji: '🦅'),
  ArabicLetterModel(letter: 'ض', word: 'ضِفْدَع', emoji: '🐸'),
  ArabicLetterModel(letter: 'ط', word: 'طَائِر', emoji: '🐦'),
  ArabicLetterModel(letter: 'ظ', word: 'ظَبْي', emoji: '🦌'),
  ArabicLetterModel(letter: 'ع', word: 'عُصْفُور', emoji: '🐤'),
  ArabicLetterModel(letter: 'غ', word: 'غَزَال', emoji: '🦙'),
  ArabicLetterModel(letter: 'ف', word: 'فِيل', emoji: '🐘'),
  ArabicLetterModel(letter: 'ق', word: 'قِطَّة', emoji: '🐱'),
  ArabicLetterModel(letter: 'ك', word: 'كَلْب', emoji: '🐶'),
  ArabicLetterModel(letter: 'ل', word: 'لَيْمُون', emoji: '🍋'),
  ArabicLetterModel(letter: 'م', word: 'مَوْز', emoji: '🍌'),
  ArabicLetterModel(letter: 'ن', word: 'نَحْلَة', emoji: '🐝'),
  ArabicLetterModel(letter: 'ه', word: 'هُدْهُد', emoji: '🦜'),
  ArabicLetterModel(letter: 'و', word: 'وَرْدَة', emoji: '🌹'),
  ArabicLetterModel(letter: 'ي', word: 'يَد', emoji: '✋'),
];

const List<String> letters = [
  "ا",
  "ب",
  "ت",
  "ث",
  "ج",
  "ح",
  "خ",
  "د",
  "ذ",
  "ر",
  "ز",
  "س",
  "ش",
  "ص",
  "ض",
  "ط",
  "ظ",
  "ع",
  "غ",
  "ف",
  "ق",
  "ك",
  "ل",
  "م",
  "ن",
  "ه",
  "و",
  "ي",
];

const List<String> lettersNames = [
  'أرنب',
  'بطة',
  'تفاحة',
  'ثعلب',
  'جزر',
  'حصان',
  'خروف',
  'دجاجة',
  'ذئب',
  'رمان',
  'زرافة',
  'سمك',
  'شجرة',
  'صورة',
  'ضفدع',
  'طائرة',
  'ظلام',
  'عنب',
  'غزال',
  'فراشة',
  'قمر',
  'كشوف',
  'لحم',
  'ماعز',
  'نحلة',
  'هلال',
  'وادي',
  'ياسمين',
];
